import {useEffect,useState} from 'react';
import {io} from 'socket.io-client';
import api from '../../services/api.js';

const resources=['profile','education','skills','projects','certificates','socials','resume','contact','chat'];
const endpoints={contact:'/contact',chat:'/chat/sessions'};
const socketOrigin=(import.meta.env.VITE_API_URL||'http://localhost:5000/api').replace(/\/api\/?$/,'');

export default function Admin(){
 const [user,setUser]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
 const [section,setSection]=useState('profile'),[records,setRecords]=useState([]),[draft,setDraft]=useState('{}'),[selected,setSelected]=useState(null),[notice,setNotice]=useState('');
 const [chatMessages,setChatMessages]=useState([]),[reply,setReply]=useState(''),[visitorTyping,setVisitorTyping]=useState(false),[uploading,setUploading]=useState(false);
 useEffect(()=>{api.get('/auth/me').then(r=>setUser(r.data.data.admin)).catch(()=>{})},[]);
 const load=async key=>{setSection(key);setSelected(null);setNotice('');setChatMessages([]);try{const r=await api.get(endpoints[key]||`/${key}`);const d=r.data.data;setRecords(Array.isArray(d)?d:d?[d]:[]);setDraft(key==='profile'||key==='resume'?JSON.stringify(Array.isArray(d)?d[0]||{}:d||{},null,2):'{}')}catch(e){setRecords([]);setNotice(e.message)}};
 const refreshSessions=async()=>{try{const r=await api.get('/chat/sessions');setRecords(Array.isArray(r.data.data)?r.data.data:[])}catch{}};
 useEffect(()=>{if(user)load(section)},[user]);
 useEffect(()=>{if(!user)return;const socket=io(socketOrigin,{withCredentials:true});socket.emit('admin:join');socket.on('chat:new-session',refreshSessions);socket.on('chat:new-message',event=>{if(selected?._id===event.sessionId){api.get(`/chat/sessions/${event.sessionId}/messages`).then(r=>setChatMessages(r.data.data)).catch(()=>{})}refreshSessions()});socket.on('chat:typing',event=>setVisitorTyping(event.typing));window.portfolioAdminSocket=socket;return()=>{socket.disconnect();delete window.portfolioAdminSocket}},[user,selected]);
 const login=async e=>{e.preventDefault();try{const r=await api.post('/auth/login',{email,password});setUser(r.data.data.admin);setError('')}catch(e){setError(e.message)}};
 const save=async e=>{e.preventDefault();try{const body=JSON.parse(draft);if(section==='profile'||section==='resume')await api.put(`/${section}`,body);else if(selected)await api.put(`${endpoints[section]||`/${section}`}/${selected._id}`,body);else await api.post(endpoints[section]||`/${section}`,body);setNotice('Saved successfully.');await load(section)}catch(e){setNotice(e instanceof SyntaxError?'Please enter valid JSON.':e.message)}};
 const remove=async id=>{try{await api.delete(`${endpoints[section]||`/${section}`}/${id}`);setNotice('Deleted.');await load(section)}catch(e){setNotice(e.message)}};
 const chooseChat=async session=>{setSelected(session);try{const r=await api.get(`/chat/sessions/${session._id}/messages`);setChatMessages(r.data.data)}catch(e){setNotice(e.message)}};
 const sendReply=async e=>{e.preventDefault();if(!selected||!reply.trim())return;try{const r=await api.post(`/chat/sessions/${selected._id}/messages`,{message:reply});setChatMessages(old=>[...old,r.data.data]);setReply('');window.portfolioAdminSocket?.emit('chat:typing',{sessionId:selected._id,typing:false})}catch(e){setNotice(e.message)}};
 const uploadFile=async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setNotice('Uploading…');try{const form=new FormData();form.append('file',file);const r=await api.post('/uploads',form);const current=JSON.parse(draft);const field=section==='resume'||section==='profile'?'resumeUrl':section==='certificates'?'fileUrl':'imageUrl';setDraft(JSON.stringify({...current,[field]:r.data.data.url},null,2));setNotice(`Uploaded. ${field} added to the JSON editor.`)}catch(e){setNotice(e.message)}finally{setUploading(false);e.target.value=''}};
 if(!user)return <main className="admin-page"><form className="admin-login" onSubmit={login}><p className="section-kicker">ADMINISTRATION</p><h1>Welcome back.</h1><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-status error">{error}</p>}<button className="button button-primary">Sign in</button><a href="/">Return to portfolio</a></form></main>;
 return <main className="admin-page"><div className="admin-top"><div><p className="section-kicker">PORTFOLIO MANAGEMENT</p><h1>Dashboard<span className="hero-period">.</span></h1><p>Signed in as {user.email}</p></div><button className="button button-secondary" onClick={async()=>{await api.post('/auth/logout');setUser(null)}}>Sign out</button></div><div className="admin-workspace"><nav className="admin-tabs" aria-label="Admin sections">{resources.map(s=><button className={section===s?'selected':''} key={s} onClick={()=>load(s)}>{s}</button>)}</nav><section className="admin-content"><div className="admin-heading"><h2>{section}</h2>{!['profile','resume','chat'].includes(section)&&<button className="button button-secondary" onClick={()=>{setSelected(null);setDraft('{}')}}>New item +</button>}</div>{notice&&<p className="form-status">{notice}</p>}
 {section==='chat'?<div className="chat-admin"><div className="chat-admin-sessions">{records.map(s=><button className={selected?._id===s._id?'selected':''} key={s._id} onClick={()=>chooseChat(s)}><strong>{s.visitorName}</strong><small>{s.visitorEmail}</small><small>{new Date(s.lastActiveAt).toLocaleString()}</small></button>)}{records.length===0&&<p className="empty-note">No chat sessions yet.</p>}</div><div className="chat-admin-conversation">{selected?<><h3>{selected.visitorName} <small>{selected.visitorEmail}</small></h3><div className="chat-admin-messages">{chatMessages.map(m=><p className={`chat-admin-message ${m.sender}`} key={m._id}>{m.message}<small>{new Date(m.createdAt||m.timestamp).toLocaleString()}</small></p>)}</div>{visitorTyping&&<p className="chat-typing">Visitor is typing…</p>}<form onSubmit={sendReply}><input value={reply} onChange={e=>{setReply(e.target.value);window.portfolioAdminSocket?.emit('chat:typing',{sessionId:selected._id,typing:Boolean(e.target.value)})}} maxLength="2000" placeholder="Write a reply…" aria-label="Reply to visitor"/><button className="button button-primary">Send reply</button></form></>:<p className="empty-note">Choose a visitor conversation.</p>}</div></div>:<>{section!=='profile'&&section!=='resume'&&<div className="admin-records">{records.map((item,i)=><article key={item._id||i}><button className="admin-record-name" onClick={()=>{if(section==='contact'){setSelected(item);setDraft(JSON.stringify({status:item.status},null,2))}else{setSelected(item);setDraft(JSON.stringify(item,null,2))}}}>{item.title||item.name||item.institution||item.platform||item.visitorName||item.subject||item._id||`Item ${i+1}`}{section==='contact'&&` · ${item.status}`}</button><button className="admin-delete" onClick={()=>remove(item._id)}>Delete</button></article>)}</div>}<form className="admin-editor" onSubmit={save}>{['projects','certificates','resume','profile'].includes(section)&&<label className="admin-file">Upload image/PDF (max 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={uploadFile} disabled={uploading}/></label>}<label>{section==='profile'||section==='resume'?'Edit configuration':section==='contact'?'Update message status':'Create or edit item'} — JSON<input type="text" readOnly value={selected?`Editing ${selected._id}`:'New record'}/><textarea aria-label="Content JSON" required rows="15" value={draft} onChange={e=>setDraft(e.target.value)} spellCheck="false"/></label><button className="button button-primary">Save changes</button></form></>}
 </section></div></main>
}
