import { useEffect,useRef,useState } from 'react';
import { MessageCircle, X, Send } from 'lucide-react';
import {io} from 'socket.io-client';
import api from '../services/api.js';
const socketOrigin=(import.meta.env.VITE_API_URL||'http://localhost:5000/api').replace(/\/api\/?$/,'');
 export default function ChatWidget({open,setOpen}){const [visitor,setVisitor]=useState({name:'',email:''}),[message,setMessage]=useState(''),[started,setStarted]=useState(false),[notice,setNotice]=useState(''),[messages,setMessages]=useState([]),[connected,setConnected]=useState(false),[typing,setTyping]=useState(false);const socket=useRef(null);const sessionId=localStorage.getItem('chatSession');
 useEffect(() => {
   if(sessionId && !started) {
     api.get(`/chat/session/${sessionId}`).then(r => {
       if (r.data.data) {
         setMessages(r.data.data.messages || []);
         setStarted(true);
       }
     }).catch(() => localStorage.removeItem('chatSession'));
   }
 }, [sessionId, started]);
 useEffect(()=>{if(!started||!sessionId)return;const connection=io(socketOrigin,{withCredentials:true});socket.current=connection;connection.on('connect',()=>{setConnected(true);connection.emit('visitor:init',{visitorToken:sessionId})});connection.on('disconnect',()=>setConnected(false));connection.on('chat:message',m=>setMessages(old=>old.some(x=>x._id===m._id)?old:[...old,m]));connection.on('chat:typing',event=>setTyping(event.typing));return()=>{connection.disconnect();socket.current=null}},[started,sessionId]);
 const start=async e=>{e.preventDefault();try{const first=message;const r=await api.post('/chat/session',{...visitor,message:first});localStorage.setItem('chatSession',r.data.data.visitorToken);setMessages([{sender:'visitor',message:first,createdAt:new Date().toISOString()}]);setMessage('');setStarted(true)}catch{setNotice('Chat is temporarily unavailable. Please leave a message through the contact form.')}};
 const send=async e=>{e.preventDefault();if(!message.trim())return;try{const r=await api.post(`/chat/session/${sessionId}/messages`,{message});setMessages(old=>old.some(x=>x._id===r.data.data.message._id)?old:[...old,r.data.data.message]);setMessage('')}catch{setNotice('Unable to send right now. Please try again.')}};
 return <><button className="chat-launch" aria-label={open?'Close chat':'Start a chat'} onClick={()=>setOpen(!open)}>{open?<X/>:<MessageCircle/>}<span>{open?'Close':'Chat'}</span></button>{open&&<aside className="chat-panel" aria-label="Portfolio chat"><header><div><span className="chat-online"/><strong>Say hello</strong><small>{started?(connected?'Connected · leave a message anytime':'Reconnecting…'):'Leave a message anytime'}</small></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close chat"><X size={18}/></button></header>{!started?<form className="chat-start" onSubmit={start}><p>Start a conversation with Amit. Leave your details and a message.</p><label>Name<input required maxLength="100" value={visitor.name} onChange={e=>setVisitor({...visitor,name:e.target.value})}/></label><label>Email<input type="email" required maxLength="254" value={visitor.email} onChange={e=>setVisitor({...visitor,email:e.target.value})}/></label><label>Message<textarea required minLength="2" maxLength="2000" value={message} onChange={e=>setMessage(e.target.value)} placeholder="What’s on your mind?"/></label><button className="button button-primary">Start chat <Send size={14}/></button></form>:<div className="chat-start"><div className="chat-transcript" aria-live="polite">{messages.map((m,i)=><p className={`chat-message ${m.sender}`} key={m._id||i}>{m.message}<small>{new Date(m.createdAt||m.timestamp||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></p>)}{typing&&<p className="chat-typing">Amit is typing…</p>}</div><form className="chat-send" onSubmit={send}><input aria-label="Type a message" maxLength="2000" value={message} onChange={e=>{setMessage(e.target.value);socket.current?.emit('chat:typing',{sessionId,typing:Boolean(e.target.value)})}} placeholder="Type a message…"/><button aria-label="Send message"><Send size={17}/></button></form></div>}{notice&&<p className="chat-notice">{notice}</p>}</aside>}</>}
